language: python
cache: pip
matrix:
  include:
    - name: "3.5"
      os: linux
      dist: xenial
      python: 3.5
    - name: "3.6"
      os: linux
      dist: xenial
      python: 3.6
    - name: "3.7"
      os: linux
      dist: xenial
      python: 3.7
    - name: "3.8-dev"
      os: linux
      dist: xenial
      python: 3.8-dev
    - name: "osx-py3.7"
      os: osx
      language: generic
      before_install:
        - brew update
        - brew upgrade python
        - python3 -m venv env
        - source env/bin/activate
  allow_failures:
    - name: "3.8-dev"
    - name: "osx-py3.7"
install:
  - pip install -U pip wheel setuptools
  - pip install -U -r requirements/dev.txt
script: pytest
deploy:
  provider: pypi
  user: constverum
  password:
    secure: HvvKX8puxOp7JCqbMWGk1GBpOWuN9ctCqYINQ6jUey6a2hNX+6gUlZSbCzHfKckPdN1SVPn6sskPNH1EgCGS1/nU109tDa7cxSxJC2fhP1g4vhwfas1c9huCqauG1I8vtLv/OVTz+2duxKeq3B0EblQ6vM/0z7b8drkCxZIG8my8oMJ94cNzyXGf0V8uvavgvRLB64TAReYAugePH/W9ZgdxRqHqbM+bp7EeMXckuMS1lM1d2Y44D4+E2OkNW0i10mlmf467MhIjmDA8nwjDNEexWfMcTxiOthSe4eZ+QcuNEdpfaLTxgssFa8sX6ExW8nC3e/EQlaIZrVmx/RlxQOFDrHPXCw5dR+KtDSyeLODWRnXJqgCOZ7HX8KA0DnC6+ejTlIyAiC/I1ZbjzTvv1lpVQ4sOYbvzGb/7i+LrAkhyjQy3yvS+mhSatf+dS2oWVhgS05fXeIRtea1r++af0BAzOolqAyN2Uyx1QVFTliECwPUsr2fvE/ZOfoLrMSrYMTI1inel2qN/56NCBEz/O60wnjFtXkBqPeP+J0eXMEcwOdQZ3q3fQTUNr5Vv9VlwLj5WgqjB8yQHAaoraSCvaXVmIkpLc5vTY0VjCWyctAN/AlqqhVl9kmWO1zqi3aXMwjNMLUT8zY30256TX4fMhLH5y0wtfYjI97CUcg0lkdQ=
  distributions: sdist bdist_wheel
  on:
    tags: true
    branch: master
    python: 3.6
